### ISSUE TITLE
About add SNS feature to shimeji4mac

### ISSUE THREAD

**Issue by AlanJager** [nonowarn/shimeji4mac#4]
I think when come to shimeji4mac, it's no doubt that itself is interesting. But when play for a long time it became really hard to play again, how do you think about the idea of get shimeji4mac some SNS feature?

**Comment by nonowarn** [comment]
It seems great but I think it shouldn't deprive simplicity of the Shimeji.

**Comment by AlanJager** [comment]
I'm trying to get a collection of tweets information and offer a interface for shimeji to implement so that should just use a may be groovy part to use the interface but will not deprive any simplicity. If I finished, I will just ask for a peer review.

**Comment by nonowarn** [comment]
Reminds me of [伺か](http://usada.sakura.vg/)… Can't wait for reviewing your work!

**Comment by AlanJager** [comment]
Roger that!

**Comment by AlanJager** [comment]
@nonowarn There is the basic design of the feature. I think in order not to deprive the shimeji4mac itself, we can just make the SNS feature on/off in the pop menu, and than a  timed task will start when the shimeji4mac was started. As a result the task will update some tweets for the shimeji to pop but actually not store inside the shimeji4mac itself, maybe just use a file to store the temporary tweets should be OK. But when shimeji need to implement the interface just one line will get it to work.

**Comment by AlanJager** [comment]
If will need to get lots of plugins, the design pattern could all follow this, so will just need several lines can get all plugins work. And just use a flag to control if a plugin should be active.

**Comment by AlanJager** [comment]
## update
I have finished basic design and could run a some demo. But remaining a problem for setting user information for shimeji to use. Because using groovy so that update the user information dynamically could be implemented so I still need some time to get a better way to solve it.
