### ISSUE TITLE
Methods lack 

### ISSUE THREAD

**Issue by Ryuusei-one** [nonowarn/shimeji4mac#8]
Missing methods 'setDockIconImage' and 'setDockMenu' in eawt.jar package in path '../shimeji4mac-master/Shimeji.app/Contents/Resources/Java/lib'?

**Comment by AlanJager** [comment]
Could you please offer more information about your macOS version?

**Comment by AlanJager** [comment]
or just change your code base to a795fb465ec56c4586b898ea54b95dfed2c81998 avoid the changes

**Comment by Ryuusei-one** [comment]
Thanks.
